@startuml Workflow One Activity Diagram
title Workflow 1: Create Playlist

start

:User selects "New Playlist";

:User clicks Submit;

repeat :Enter UserId and Playlist Name;
    :Click Submit;

    if (Input valid?) then (Yes)

        :Call PlaylistController.createPlaylist(userId, playlistName);
        :Controller calls PlaylistDataProvider.createPlaylist();
        :DAL calls stored procedure CreatePlaylist;
        :Database creates playlist;
        :Return playlistId;

        :Show success message;
    else (No)
        :Show error message;
    endif

' *Won't let me put text on the merge diamond*
repeat while (User wants to create another playlist?)

:User clicks Back when done;

stop
@enduml
